# Generated by Django 6.0.5 on 2026-06-23 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(max_length=255)),
                ('teacher_name', models.CharField(blank=True, max_length=180)),
                ('school', models.CharField(max_length=255)),
                ('class_name', models.CharField(max_length=160)),
                ('year', models.CharField(max_length=4)),
                ('bimester', models.CharField(max_length=12)),
                ('bimester_label', models.CharField(max_length=40)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('class_average', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('freq_media', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('risk_count', models.PositiveIntegerField(default=0)),
                ('risk_pct', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('learning_index', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('metrics_snapshot', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-processed_at'],
                'indexes': [models.Index(fields=['school', 'class_name', 'year', 'bimester'], name='analyzer_pr_school_1c3c5e_idx'), models.Index(fields=['processed_at'], name='analyzer_pr_process_b849a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=220)),
                ('ra', models.CharField(blank=True, max_length=40)),
                ('active', models.BooleanField(default=True)),
                ('total_faltas', models.PositiveIntegerField(blank=True, null=True)),
                ('average', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('level_key', models.CharField(blank=True, max_length=20)),
                ('level_label', models.CharField(blank=True, max_length=40)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='analyzer.processedreport')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=12)),
                ('subject_name', models.CharField(max_length=80)),
                ('grade', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='analyzer.studentsnapshot')),
            ],
            options={
                'ordering': ['subject_code'],
            },
        ),
        migrations.CreateModel(
            name='SubjectSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=80)),
                ('average', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('level_key', models.CharField(blank=True, max_length=20)),
                ('level_label', models.CharField(blank=True, max_length=40)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='analyzer.processedreport')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddIndex(
            model_name='studentsnapshot',
            index=models.Index(fields=['ra'], name='analyzer_st_ra_87c0b9_idx'),
        ),
        migrations.AddIndex(
            model_name='studentsnapshot',
            index=models.Index(fields=['name'], name='analyzer_st_name_fdb0c5_idx'),
        ),
        migrations.AddIndex(
            model_name='studentgrade',
            index=models.Index(fields=['subject_code'], name='analyzer_st_subject_8b1af8_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectsnapshot',
            index=models.Index(fields=['code'], name='analyzer_su_code_c61dc0_idx'),
        ),
    ]
